---
deployment:
  tasks:
    - export DEPLOYPATH=/home/accionintegraorg/Platform
    - export REPOPATH=/home/accionintegraorg/Repositories/accion-integra
    - /bin/rm -Rf ${DEPLOYPATH}_old
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' ${REPOPATH}/ ${DEPLOYPATH}
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;